version: "3.9"

services:
  app:
    build:
      context: .
    container_name: laravel_app
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:8
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: Kmelo23k!
      MYSQL_DATABASE: silva
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel: